### ISSUE TITLE
Initial development roadmap

### ISSUE THREAD

**Issue by LukasKalbertodt** [LukasKalbertodt/luten#1]
Quick notes on the initial development. 

### Phase 0: Playground & Login (done in 85586986b1a7e878dad1e6fe72305077d360a347) ✔

The idea is to lay a foundation for everything before moving on. The only real implemented feature is a more or less finished login system. In this phase my git history/commit messages are bad and all over the place.

- [x] DB connection pooling via `r2d2` ([`r2d2-diesel`](https://github.com/diesel-rs/r2d2-diesel))
- [x] Session management
  - [ ] *NTH*: invalidate/remove old sessions from DB 
- [x] Integrate CSS preprocessor into build pipeline (including Travis). Probably using SCSS.
- [x] Proper error handling
- [x] Support for multiple languages (postponed: need to have more code actually outputting stuff to decide)
- [x] Cleanup 

### Phase 1: Finish login system (PR #3) ✔
From now on, development will happen on another branch and git history is not horrible anymore.

- [x] Improve login page
  - [x] Proper style
  - [x] Possibility to select a login provider
  - [x] Proper feedback on failure
- [x] Finish "Account" nav item
  - [x] Extend on hover
  - [x] Logout button
  - [x] Lin to "settings"
- [x] Empty/dummy "settings" route
- [x] Support for multiple languages

### Phase 2: User roles (PR #4) ✔
We have admins, tutors and students. We need to store that in the database and write functions to easily check the role and different permissions. Maybe create types `AuthAdmin`, `AuthTutor` and `AuthStudent` as request guards?

### Phase 3: Prepare system for different "states" of application (PR #5) ✔
The application can be in different states/modes: in the first state, students can select time slots and so on. This can be locked after a deadline and after a while the system is switched to yet another state: the standard "running" state.

- [x] Make routes easily dispatch between states
- [ ] ~~Auto switching states? Cronjobs? We probably want to execute several things regularly!~~ (**postponed**: not hugely important right now, I might want to develop a dedicated schedule crate for this)
- [X]  ~~**Later**: install 404 handler which shows an appropriate toast if the app is frozen. OR:~~
- [ ] ~~**Later**: install fairing which redirects to /frozen~~

### Phase 4: Start designing the routes for the first state
In the first state students and tutors can rate time slots and state certain preferences. Those are later evaluated by a solver to find the best assignment.

- [ ] How to get the configuration data into the system?
  - e.g. available time slots
- [ ] Create page to rate time slots
- [ ] Designing the page for students
- [ ] Design the page for tutors
- ...

---

### After briefing with colleagues 
- [ ] Think about testing 
- [x] Write documentation (how to start working on this project/run this project)
- [ ] Make nav bar usable on mobile devices (#7) 

### Other ideas
- Panic catcher which sends a mail to me when running in prod mode
- We might want to make the `error-chain` Errors *unrecoverable* only and use `Result<StdResult<...>>` for recoverable and unrecoverable errors... *sigh*, error handling is hard.

**Comment by LukasKalbertodt** [comment]
This issue is superfluous now. Separate issues for all unfinished points on this list have been created.
