### ISSUE TITLE
Tracking issue: inline TODO comments

### ISSUE THREAD

**Issue by LukasKalbertodt** [LukasKalbertodt/luten#2]
There are quite a few `// TODO` comments right now. While eventually all of those should be removed and converted into GH issues, right now it's still handy to have those around. However, I'll try to list them here to avoid forgetting an issue.

- [ ] `README.md`: Write a better summary
- [ ] `build.rs`: use Rocket's environment
- ~~`bin/manage_db.rs`: find user by username~~ #35 
- [ ] `db/mod.rs`: maybe tweak r2d2 config if necessary
- [ ] `db/mod.rs`: maybe install another error handler for db pool
- [x] `login/mod.rs`: reactivate "Associations" feature of diesel
- ~~`login/routes.rs`: redirect to original request path~~ #34
- [x] `template/mod.rs`: Unhide help on login page?
